version: '3.8'
services:
  client:
    build: ./
    image: ${CLIENT_IMAGE_NAME}
    container_name: ${CLIENT_CONTAINER_NAME}
    ports:
      - ${CLIENT_PORT_EXTERNAL}:${CLIENT_PORT_INTERNAL}
    env_file:
      - ./.env
